### PR TITLE
Use u16 countType for shortString

### PR DESCRIPTION
**Pull request by UMRnInside**
This could fix https://github.com/PrismarineJS/mineflayer/issues/2408 and https://github.com/PrismarineJS/node-minecraft-protocol/issues/974
Review required, as I'm not sure if it accidentally breaks something (that depends on signed string size).

### CODE REVIEW

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-nbt/blob/538a8614c1bad49a2f42545b97f577bfe466f1d0/nbt.js#L6 you will need to adapt this line (it currently transforms i to li for the little endian case, need the same for u to lu)

Also @extremeheat does this change make sense to you ? (Are short string prefixed by unsigned shorts in bedrock?)

**Comment by rom1504** [comment]
If this change is correct, i think we should also check all the i32 used as count type. There are quite a few.
Finding the java code for this and checking against it would be good.

**Comment by extremeheat** [comment]
I looked around and it seems most places read/write this data as a signed 16-bit integer (normal "NBT Short")

* https://github.com/tryashtar/fNbt/blob/2be4eaa701aeedda2c2edd8052d46cc3eaca625a/fNbt/NbtBinaryReader.cs#L85
* https://github.com/twoolie/NBT/blob/6f43e8758d66374807e5f31d23fe2c9dc1d996b0/nbt/nbt.py#L144
* https://github.com/pmmp/NBT/blob/1a73be856840e521ff27bbdcfa44b1f54fb30892/src/BaseNbtSerializer.php#L173

However going through the Minecraft Java source code, the NBT Strings are written as UTF8 strings with the Java stream writer class, which writes the length integer as signed (as all numbers in Java are signed), however when reading it seems Java parses the number as an unsigned 16-bit integer

* https://github.com/extremeheat/extracted_minecraft_data/blob/client1.18.1/client/net/minecraft/nbt/StringTag.java#L13-L65
* https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/io/DataInputStream.java#L594

As for bedrock, most implementations also limit the string length to < signed int16's max value
* https://github.com/Sandertv/gophertunnel/blob/b6af5c5f774c2e48835c55343e317af24152906d/minecraft/nbt/encoding.go#L214

Haven't looked at the disassembled source for bedrock for this, but even if bedrock were to read this as signed, a negative length would be invalid so I think this change shouldn't affect much. The other numeric arrays' length are still signed.

**Comment by rom1504** [comment]
Ok let's go with that

**Comment by rom1504** [comment]
Thanks for looking into it

**Pull request merged**
