### PR TITLE
Make it work with module bundlers

### LINKED ISSUE #17: Breaks with module bundlers
In [nbt.js#L8](https://github.com/PrismarineJS/prismarine-nbt/blob/e8fb5e97a384ce4b11c6f380f455ac7c07fa41b6/nbt.js#L8), using the `fs` module to read files is not module bundler friendly and will break when this package is bundled using webpack/etc.

### PR DESCRIPTION
**Pull request by Luminess**
fix #17

### CODE REVIEW

**Comment by rom1504** [comment]
Ha !
You found a weakness in the tests.
That will not work because by doing that you change the require('./nbt') object which is global to the node instance.
It seems that the test don't test the mcpe part.

The way to make it actually work would be to clone that object.

Well I'll fix the tests anyway.

And, about bundlers, I think it already works thanks to that browserify fs plugin.

But I'll check all this better ;)

**Comment by rom1504** [comment]
indeed it already works with browserify, see https://github.com/PrismarineJS/prismarine-nbt/blob/master/package.json#L29

**Comment by Luminess** [comment]
Gah. I can't figure out how to make it work with my webpack setup. Any piece of code that tries to import by using fs.read* will be ignored by webpack and said code would end up trying to read from the disk root in the bundle.

**Comment by rom1504** [comment]
Rethinking about it, that works. The .replace doesn't change anything.

**Pull request merged**
