### PR TITLE
reimplement using protodef

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
Remaining here:
* [ ] fix nbt.Writer and nbt.Reader tests (basically move them to ProtoDef for most of them)
* [ ] move mapper to protodef (after making sure it makes sense for nmp too)
* [ ] generalize string in protodef and use that instead of shortString

**Comment by rom1504** [comment]
All done, the types are available in nbt.proto.types. I think it's probably best to define compound manually here.

Waiting for https://github.com/roblabla/ProtoDef/pull/23 to be merged and a new protodef release.

**Comment by rom1504** [comment]
Ready to be merged.

**Comment by rom1504** [comment]
@roblabla so, can this be merged ?

**Comment by roblabla** [comment]
Could you rebase this before merging ?

**Comment by rom1504** [comment]
I'm not sure which commits should be squashed, keeping it at different commits seems to make more sense to me here.

**Comment by rom1504** [comment]
alright rebase done, ready to merge @roblabla

**Pull request merged**
