### PR TITLE
add nbt builder

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by extremeheat** [comment]
You can spread it into module.exports or even paste it into the export that way you don’t need extra import/destructure code,
`
{
  parse,
  ...builder
}
`

**Comment by u9g** [comment]
> You can spread it into module.exports or even paste it into the export that way you don’t need extra import/destructure code,
> `{ parse, ...builder }`

done :)

**Review by rom1504 — APPROVED** [review]
looks good

**Comment by GroobleDierne** [comment]
It seems that NBTDouble and NBTLong are missing.

**Pull request merged**
