### PR TITLE
Added writeJsObject()

### PR DESCRIPTION
**Pull request by GroobleDierne**
Added a function that takes a javascript object, convert it to the nbt format and write it.

This is an example of the result of a convertion:
```javascript
let parsedObj = parseJsObjectt({
  Data: {
    RandomSeed: '0L',
    Difficulty: '0b',
    BorderSize: '60000000.0d',
    GameRules: {
      announceAdvancements: true
    },
    ServerBrands : [],
    RandomArray: ['hello', 'I am', 'a test array']
})
console.log(JSON.stringify(parsedObj))
```
will result in
````
{
  "type": "compound",
  "value": {
    "Data": {
      "type": "compound",
      "value": {
        "RandomSeed": {
          "type": "long",
          "value": [
            0,
            "0"
          ]
        },
        "Difficulty": {
          "type": "byte",
          "value": "0"
        },
        "BorderSize": {
          "type": "double",
          "value": "60000000.0"
        },
        "GameRules": {
          "type": "compound",
          "value": {
            "announceAdvancements": {
              "type": "string",
              "value": "true"
            }
          }
        },
        "ServerBrands": {
          "type": "list",
          "value": {
            "type": "end",
            "value": []
          }
        },
        "RandomArray": {
          "type": "list",
          "value": {
            "type": "string",
            "value": [
              "hello",
              "I am",
              "a test array"
            ]
          }
        }
      }
    }
  }
}
````

### CODE REVIEW

**Comment by u9g** [comment]
when adding to the docs, make sure to note that if you are doing a byte or something that you need to add the 'b' to the end of the string

**Comment by GroobleDierne** [comment]
Of course, I'll do a proper documentation and add tests.

**Comment by extremeheat** [comment]
I think this is okay, having a shorter syntax can be nice. But it also does add some fragmentation, we have the protodef object format used internally, simplify format which removes encapsulation, then this to kind of reverse the simplify process. They’re not really interoperable. So I’m not sure there’s much practical benefit. There is #39 to return something from simplify that can be written back, but not a simple thing to solve.

**Comment by GroobleDierne** [comment]
Yeah while javascript isn't strongly typed it's very difficult to do that without adding extra informations such as suffixes or extra fields with type information.

**Comment by rom1504** [comment]
I'm not very convinced by this.
This is a variation of https://www.npmjs.com/package/mojangson
what use case are you trying to solve with this ?

**Comment by extremeheat** [comment]
The array issue sounds like something that should be fixed separately instead. Using a custom string-based format like here isn't reliable. What if you *want* it to be a string and not be type coerced? For clarity, why not just wrapper functions?

```ts
var nbt = {
  short(value: number) { return { type: 'short', value } },
  byte(value: number) { return { type: 'byte', value } },
  string(value: string) { return { type: 'string', value } },
  comp(value) { return { type: 'compound', value } },
  list(...value) {
    const type = value[0]?.type ?? 'end'
    return { type: 'list', value: { type, value } }
  }
}

writePlayerNbt({
  Air: nbt.short(300),
  Armor: nbt.list(
    nbt.comp({ Count: nbt.byte(0), Damage: nbt.short(0), Name: nbt.string("") }),
    nbt.comp({ Count: nbt.byte(0), Damage: nbt.short(0), Name: nbt.string("") }),
    nbt.comp({ Count: nbt.byte(0), Damage: nbt.short(0), Name: nbt.string("") }),
  ),
})
```

**Comment by GroobleDierne** [comment]
Yes, It can be added so users have the choice and can combine both.

**Comment by extremeheat** [comment]
That sounds pretty bad

**Comment by rom1504** [comment]
I like the NBT builder helper function idea.
This could be a good solution to that making it easy to build and edit NBT use case.

**Comment by GroobleDierne** [comment]
Why has it been closed?

**Comment by GroobleDierne** [comment]
I don't have much time because of my exams, but I haven't abandoned the pr.

**Comment by rom1504** [comment]
It would need to be completely rewritten to avoid integrating this format and instead provide builder functions.
I can reopen if you want to do this in this PR

**Comment by GroobleDierne** [comment]
Ok I'll do that

**Comment by rom1504** [comment]
#48 is a better solution for this

**Pull request closed without merging**
