### PR TITLE
Added missing JavaScript equivalent for TypeScript TagType enum

### LINKED ISSUE #40: TagType enum cannot be imported
Hi!

There is an `index.d.ts` file attached the package, which is very useful for implementations that use TypeScript. These types work fairly nice, with the exception of one: the `TagType` enum. TypeScript enums are not exported properly when defined in a `d.ts` file, as they are not transpiled to the `index.js` file, nor are they a declared type using `type`.

See the example below:
```typescript
import { TagType } from "prismarine-nbt";

console.log(TagType); // "undefined"
console.log(TagType.Int); // "TypeError: Cannot read property 'Int' of undefined"
```

The issue here is that an enum will be transpiled to JavaScript as it describes some functionality. However, the contents of the `.d.ts` file are not transpiled. See for example this [Reddit post](https://www.reddit.com/r/typescript/comments/dp7zd5/enum_or_enumlike_type_in_a_declaration_file/) on the topic. This issue makes it difficult to use the TypeScript typings effectively, as the `Tags` are indexed by the enum, e.g. `Tags[TagType.Int]`.

A (temporary) fix that I have employed is to copy the enum over to a `.ts` file in my own project. However, it'd be nicer to be able to use the one provided by the package.

### PR DESCRIPTION
**Pull request by McJeffr**
Fixes #40:

- Missing JavaScript equivalent of TypeScript enum.

### CODE REVIEW

**Comment by McJeffr** [comment]
I'll address the failing tests, I did not realize those were there, my bad.

**Comment by rom1504** [comment]
please add doc

is it useful ?

**Comment by McJeffr** [comment]
Unsure how to add documentation to this, as it is a bugfix, not a new feature. See #41 for more information.

As for if it is useful, it basically allows developers working in TypeScript to use the TagType enum that is defined in the typings, but isn't actually compiled along with the bundle as enums need to be transpiled.

**Review by rom1504 — APPROVED** [review]

**Comment by rom1504** [comment]
I don't see the point but not hurtful, merging

**Pull request merged**
